### ISSUE TITLE
MultiDesk test doesn't work properly since Shipping Status constants were changed

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#156]

**Comment by tsember** [comment]
but the bug looks to do with sleeping and DateTimeTools. 

I think this is going to be some kind of "make clean" issue because eclipse complained about DateTimeTools until i did a clean in it.

**Comment by tsember** [comment]
The sleep in ShipmentDesk doesn't work properly when it is called in by the MultiDeskTest.

yet it works in the ShipmentDeskTest.

but since it crashes after all the tests pass, and it correctly tests them, it just executes poorly.

I am not attempting anything until I hear what happens on Jeff's machine when he does "rake test". It is not interfering with any functionality.



Exception in thread "Thread-3" Exception in thread "Thread-2" java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1327)
	at java.util.TreeMap.firstKey(TreeMap.java:290)
	at java.util.TreeSet.first(TreeSet.java:394)
	at com.tsember.DateTimeTools.sleepForAccelerated(DateTimeTools.java:211)
	at com.tsember.DateTimeTools.sleep(DateTimeTools.java:38)
	at com.tsember.shipmentDesk.ShipmentDesk.processDeskAux(ShipmentDesk.java:132)
	at com.tsember.shipmentDesk.ShipmentDesk.processDesk(ShipmentDesk.java:84)
	at com.tsember.shipmentDesk.ShipmentDesk.execute(ShipmentDesk.java:40)
	at com.tsember.integration.MultiDeskTest$5.run(MultiDeskTest.java:237)
java.util.NoSuchElementException
