### ISSUE TITLE
Define what initial files should be present so application runs without error

### ISSUE THREAD

**Issue by jpsember** [tsember/freight-portal#27]
On my machine, I'm having this output, and would like to know how to fix things so it doesn't crash:
```
| INFO: ---
| INFO: ---  Logger initialized
| INFO: ---
| INFO: Initializing the BareBonesDesk...
| INFO: /Users/home/.freight-portal-config.json
| INFO: 
| INFO:     {  }
| INFO: Successfully finished initializing the BareBonesDesk...
| INFO: BareBonesDesk has started up and is processing requests...
Exception in thread "main" java.lang.IllegalArgumentException: missing value for key input_directory
	at com.tsember.json.JSMap.getValueFor(JSMap.java:296)
	at com.tsember.json.JSMap.get(JSMap.java:122)
	at com.tsember.BareBonesDesk.processDesk(BareBonesDesk.java:98)
	at com.tsember.BareBonesDesk.main(BareBonesDesk.java:33)
```

**Comment by jpsember** [comment]
@tsember , can you give some advice?

**Comment by jpsember** [comment]
Ok, I think I gathered that my config file should look something like:
```
.freight-portal-config.json
| INFO: 
| INFO:     {  "input_directory" : "/home/Desktop/freight_data/input_directory",
| INFO:       "output_directory" : "/home/Desktop/freight_data/output_directory"
| INFO:     }
```

**Comment by jpsember** [comment]
...For now, here's what's required...


The config file by default is at `~/.freight-portal-config.json` and should contain a json map as follows:

```
{  "input_directory" : "/...../input_directory",   **absolute path!**
  "output_directory" : "/...../output_directory"   **absolute path!**
}
```
